name: Run Api.Write

on:
  schedule:
    - cron: '32 11 * * 1-5'
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Install requests and xlsxwriter
      run: |
        pip install requests xlsxwriter
    - name: Run api.Write
      env:
        CITY: ${{ secrets.CITY }}
        EMAIL: ${{ secrets.EMAIL }}
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        GH_REPO: ${{ github.repository }}
        APP_NUM: ${{ secrets.APP_NUM }}
        MS_TOKEN_1: ${{ secrets.MS_TOKEN }}
        CLIENT_ID_1: ${{ secrets.CLIENT_ID }}
        CLIENT_SECRET_1: ${{ secrets.CLIENT_SECRET }}
      run: |
        python ApiOfWrite.py
    - name: update_or_create report.api.write.txt
      run: date +"%Y-%m-%d %H:%M:%S %z" > report.api.write.txt
    - name: commit report
      run: |
        git config --global user.name 'msdev2023'
        git config --global user.email 'msdev2023@outlook.com'
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
        git add report.api.write.txt
        git commit -am "Report: Api.Write"
        git push
