name: Run Api.Read

on:
  schedule:
    - cron: '12 10,16 * * 1-5'
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Install requests
      run: |
        pip install requests
    - name: Run api.Read
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        GH_REPO: ${{ github.repository }}
        APP_NUM: ${{ secrets.APP_NUM }}
        MS_TOKEN_1: ${{ secrets.MS_TOKEN }}
        CLIENT_ID_1: ${{ secrets.CLIENT_ID }}
        CLIENT_SECRET_1: ${{ secrets.CLIENT_SECRET }}
      run: |
        python ApiOfRead.py
