name: Run Api.Read

on:
  schedule:
    - cron: '12 10,16 * * 1-5'
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Install requests
      run: |
        pip install requests
    - name: Run api.Read
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        GH_REPO: ${{ github.repository }}
        APP_NUM: ${{ secrets.APP_NUM }}
        MS_TOKEN_1: ${{ secrets.MS_TOKEN }}
        CLIENT_ID_1: ${{ secrets.CLIENT_ID }}
        CLIENT_SECRET_1: ${{ secrets.CLIENT_SECRET }}
      run: |
        python ApiOfRead.py
    - name: update_or_create report.api.read.txt
      run: date +"%Y-%m-%d %H:%M:%S %z" > report.api.read.txt
    - name: commit report
      run: |
        git config --global user.name 'msdev2023'
        git config --global user.email 'msdev2023@outlook.com'
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
        git add report.api.read.txt
        git commit -am "Report: Api.Read"
        git push
