name: Update Token

on:
  release:
    types: [published]
  push:
    tags:
    - 'v*'
  #  branches:
  #    - master
  schedule:
    - cron: '10 15 * * 1,3,5'
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Install requests and nacl
      run: |
        pip install requests PyNaCl
    - name: Update secrets
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        GH_REPO: ${{ github.repository }}
        APP_NUM: ${{ secrets.APP_NUM }}
        MS_TOKEN_1: ${{ secrets.MS_TOKEN }}
        CLIENT_ID_1: ${{ secrets.CLIENT_ID }}
        CLIENT_SECRET_1: ${{ secrets.CLIENT_SECRET }}
      run: |
        python UpdateToken.py
